### ISSUE TITLE
Update virtualbox fails

### ISSUE THREAD

**Issue by colmprunty** [StefanScherer/docker-windows-box#19]
Hi, I'm trying to run the VM on Virtualbox, and I'm hitting the below issue:

![](http://i.imgur.com/s73HZqt.png)

The URL for the .iso is correct, I can download it on my own machine. In order to get to this point though, I'm hitting issue #15, where the VM gets stuck on Windows updates and eventually times out, leaving the host waiting for winrm to become available. I've killed the windows updates script on the VM and run the enable winrm script manually. It's after this point that it dies.

**Comment by KevinBurton** [comment]
I use the command to use an existing image (iso) and now I get an immediate error from Fusion that /dev/vmmon could not be found. And when I try to start up Fusion I get a file not found error/dialog box. Given I already have an iso file is there something that I can tell the Fusion support people that packer does so that I can isolate the problem to Fusion?

**Comment by KevinBurton** [comment]
OK VMWare says that I should be using 8.5.5 instead of the latest. But now I am getting an error on reading the license key. What is the variable that I need to set for the license key?

**Comment by KevinBurton** [comment]
I got past the license key issue but now it seems something has changed with the version of Fusion that I am running (8.5.5). I get a dialog box that until I click either OK or Cancel the installation/build process does not continue. I have attached a screenshot of the message that I am seeing.

<img width="549" alt="screen shot 2017-04-24 at 9 18 11 pm" src="https://cloud.githubusercontent.com/assets/2643566/25366296/5939eb04-2934-11e7-871f-d8c7859927f6.png">

But if I click on the OK or Cancel button it seems that I get into a infinite loop on the packer build process continually printing out: 
vmware-iso: Running
vmware-iso: Running

Should I just be patient?

Thank you.

Kevin

**Comment by StefanScherer** [comment]
@colmprunty I'll try a virtualbox buuld on Windows today to check if I can reproduce your problem. 
@KevinBurton The dialog is only that VMware tools have recognized the HiDPI/Retina display. Just leave it. The final Vagrant box normally boots with Retina enabled.

**Comment by StefanScherer** [comment]
@colmprunty Today I rebuilt a VirtualBox VM on a Windows 7 host, using VirtualBox 5.1.20, packer 1.0.0 and the latest changes in my packer-windows repo. It also installs the 5.1.20 guest additions.

**Comment by colmprunty** [comment]
Thanks Stefan, I'll try and spin it up this week if I get a chance and report back.

**Comment by StefanScherer** [comment]
I'm closing this one as I expect everything works fine :-)
