### ISSUE TITLE
Duplicates of docker.exe and dockerd.exe in search path

### ISSUE THREAD

**Issue by sitano** [StefanScherer/docker-windows-box#2]
The main docker daemon run from c:\Program Files\docker*.
Second copy sits in c:\Windows\System32.
Update script to latest version uploads dockers only to c:\Windows\System32.

**Comment by StefanScherer** [comment]
@sitano Thanks. I'll fix that. Sure, the latest binaries should overwrite the files in ProgramFiles\docker
