### ISSUE TITLE
vagrant up?

### ISSUE THREAD

**Issue by KevinBurton** [StefanScherer/docker-windows-box#20]
I am new to vagrant and packer so forgive me. I  successfully did all four steps mentioned in the README.md. 

- git clone https://github.com/StefanScherer/packer-windows
- cd packer-windows
- packer build --only=vmware-iso windows_2016_docker.json
- vagrant box add windows_2016_docker windows_2016_docker_vmware.box

Now I try 'vagrant up' and get
```
$ vagrant up
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.
$ 
```
I must have missed a step. Is there any possibility of getting some high-level explanation for the last two steps and what I need to do to be able to run 'vagrant up' successfully.

Thank you.

**Comment by StefanScherer** [comment]
You have to clone/download this github repo and change the current dir into it so Vgrant can find the Vagrantfile and spin up the VM.

**Comment by KevinBurton** [comment]
Isn't that the first step?

**Comment by StefanScherer** [comment]
Before vagrant up you have to go to the docker-windows-box folder where the Vagrantfile is. If you typed the packer build steps then a cd .. should do that.

**Comment by StefanScherer** [comment]
I'll close this issue. If you still need help feel free to reopen it.
