### ISSUE TITLE
Modify packer to use iso file

### ISSUE THREAD

**Issue by KevinBurton** [StefanScherer/docker-windows-box#21]
The packer build process takes a long time for me and one way to speed things up would be to use an existing iso file. But being unfamiliar with 'packer' I am not sure how to modify the build script to do so.

**Comment by StefanScherer** [comment]
You can add parameters to the packer build, have a look at my command line that I use with local ISO files:

https://github.com/StefanScherer/packer-windows/blob/my/build_windows_2016_docker.sh#L5

**Comment by KevinBurton** [comment]
Thank you. What does 'autounattend' do?

**Comment by StefanScherer** [comment]
Each `--var key=value` replaces the default given in the json file. With this I can use a different autounattend.xml file without modifying my Git repo (eg. product keys inserted). Just leave the option away to use the default xml file.

**Comment by KevinBurton** [comment]
Thank you.
