### ISSUE TITLE
Question about overlay network

### ISSUE THREAD

**Issue by chrisjstevenson** [StefanScherer/docker-windows-box#22]
Hi Stefan,

I'm trying to use your example for some Windows Container stuff at work, I'm having trouble getting a definitive answer on whether routing mesh supported in Windows 2016 yet?  

I'm running Docker 17.03.1-ee-3 on Windows Server 2016 (os build 14393.1358).  

Thanks for all the work you are doing in this area!

**Comment by pennywisdom** [comment]
From [here ](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/swarm-mode) and various other sources the official github repos.

> Routing mesh for Windows docker hosts is not yet supported, but will be coming soon. 

This kind of reduces the total impact of swarm mode on windows nodes as is but the impression is that it will be supported pretty soon now.

**Comment by StefanScherer** [comment]
Correct. Routing mesh is still missing. It's worth to join the Windows Server Insider preview as it should be available first before landing in an official Windows update.

**Comment by chrisjstevenson** [comment]
Thanks for the info, I'll keep posted
