### ISSUE TITLE
different vagrantfile

### ISSUE THREAD

**Issue by alexivkin** [StefanScherer/docker-windows-box#25]
Great work on the box! It's very helpful for getting windows docker running on linux. 
I've noticed however that your [latest vagrant repo](https://app.vagrantup.com/StefanScherer/boxes/windows_2016_docker) is behind this git hub repo. The vagrantfile vagrant pulls does not have vram, clipboard etc mods for virtualbox.

**Comment by alexivkin** [comment]
Just realized that you switched to packer in 17.10, and the one in this repo is actually older than the one in vagrantcloud. Still there is a regression between 17.10 and 17.03. The packer version is missing the vram, clipboard and video settings that used to be there.

Could you please update this repo with the latest sources? And please disable windows 'telemetry' by default.

**Comment by StefanScherer** [comment]
Thanks.

I've switched to Windows Server Core with the latest windows_2016_docker box. The Vagrantfile template for server core https://github.com/StefanScherer/packer-windows/blob/my/vagrantfile-windows_2016_core.template does not have these settings. Do you think these should be added there as well?

For this repo where a Windows Server with Desktop is need I think I'll switch to a windows_2016 template and install Docker through Vagrant provisioning.

**Comment by alexivkin** [comment]
Yes, the default 8M vram makes the screen too little even for rdp, and not having a bidirectional clipboard is a hindrance. Is there any way the vagrantcloud repo can reference the source template from github? It's difficult to find which one is the source for the vagrant vm. The sources help prove there is no 'extra' baggage in the vm.

**Comment by StefanScherer** [comment]
OK, I'll add these settings.
Well, I don't have a CI pipeline for that to run these Packer builds in a better way, so there always is some manual work and I forget to tag the sources etc. ¯\_(ツ)_/¯

**Comment by StefanScherer** [comment]
Updated the packer templates. If you use the current baseboxes then add your vram settings in Vagrantfile. 
Next baseboxes will have this setting.
