### ISSUE TITLE
Not really an issue - But missing item in pre-req

### ISSUE THREAD

**Issue by dmdb0101** [StefanScherer/docker-windows-box#28]
Hello, I just wanted to point out that it would be great to add in the readme pre-requisites to include that VMWare needs to be installed to run this command: packer build --only=vmware-iso windows_2016_docker.json.

thank you for this project though. this is awesome

**Comment by StefanScherer** [comment]
Thanks. I love this feedback as it gives me a better understanding what is missing or unclear. 
Sure you can use another hypervisor like VirtualBox or Hyper-V. I‘ll update the Readme.

**Comment by StefanScherer** [comment]
I have simplified the setup. The Vagrantfile references the already available Vagrant box in Vagrant Cloud, so you don't need the packer build step.

Fixed with 5d7ef779b09c5dcc1faed228e01484bb02cce999
