### ISSUE TITLE
Problem using your docker-windows-box

### ISSUE THREAD

**Issue by ybello33** [StefanScherer/docker-windows-box#29]
Hello
i'm getting an error ..
➜  windows-docker-machine git:(master) vagrant box add windows_2016_docker_virtualbox windows_2016_docker_virtualbox.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'windows_2016_docker_virtualbox' (v0) for provider:
    box: Downloading: windows_2016_docker_virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/ybello/windows-docker-machine/windows_2016_docker_virtualbox.box
=================================================
i also verify that big *.box file is in the packer-windows directory where it;'s called the packer build command.
-rw-r--r--   1 ybello  staff   5.9K May 13 01:09 windows_2016_docker.json
-rw-r--r--   1 ybello  staff   2.3K May 13 01:09 windows_2016_docker_azure.json
-rw-r--r--   1 ybello  staff    10G May 13 13:58 windows_2016_docker_virtualbox.box
-rw-r--r--   1 ybello  staff   4.3K May 13 01:09 windows_2016_hyperv.json
===========================================================
it's seams there is a problem - can anyone can help ?
also please note that suddenly the new VM inside the virtualbox that was created earlier by the build is despair

please help - i really need this work 

thanks

**Comment by StefanScherer** [comment]
So you managed to start the VM, congrats.  Is this issue solved?

**Comment by ybello33** [comment]
Hi - yes of course 
now i have a problem to access into it - i can get the RDP screen but the user/pass is not working
