### ISSUE TITLE
Blank black screen with cmd only

### ISSUE THREAD

**Issue by iDVB** [StefanScherer/docker-windows-box#30]
I managed to get `vagrant up` to complete successfully with no errors.. but once its up and running its just a black window with a single cmd open?

Am I missing something? Should there not be a UI version with windows bar etc?

![image](https://user-images.githubusercontent.com/189506/41509324-1322733a-7220-11e8-935e-4734f2a82695.png)

**Comment by StefanScherer** [comment]
Welcome to Windows Server Core. 
At least notepad is there 😜

**Comment by StefanScherer** [comment]
The box StefanScherer/windows_2016_docker is Core only.

**Comment by iDVB** [comment]
Hmm, doh.. what I’m going for was something I can build windows traditional
.Net Docker images with. Was hoping to do it from inside VS.

I have a Mac so wanted to us VM.

Any thoughts?

**Comment by StefanScherer** [comment]
The other box StefanScherer/windows_2016 is with Desktop. 
Either use this and install Docker with the provision scripts manually or adjust the packer-windows templates to start with the Desktop autounattend.xml instead of the Core one.

**Comment by iDVB** [comment]
Thx @StefanScherer, not sure what `StefanScherer/windows_2016` is .... I don't see any repo on you with that name?

**Comment by StefanScherer** [comment]
It‘s the name of a Vagrant box you can download from Vagrant Cloud. 
If you prefer to build your own it‘s the windows_2016.json template in my packer-windows repo.
