### ISSUE TITLE
Docker Daemon ExecStart initial value has changed?

### ISSUE THREAD

**Issue by Minimonium** [StefanScherer/docker-windows-box#33]
`docker-swarm-init.sh` isn't working because it expects this:
```
ExecStart=/usr/bin/dockerd -H fd://
```
but since recently gets this:
```
ExecStart=/usr/bin/dockerd -H unix://
```
Don't know why, but to be sure `sed` should be fixed to a more general case?

**Comment by StefanScherer** [comment]
Thanks. Wow that change also brings trouble in this repo. 
The problem will be fixed in https://github.com/docker/docker-ce-packaging/pull/257

**Comment by Minimonium** [comment]
Thanks for the info!
