### ISSUE TITLE
Latest docker

### ISSUE THREAD

**Issue by sitano** [StefanScherer/docker-windows-box#4]
Latest docker would not work due to https://github.com/docker/docker/issues/25176

Need to either reinstall / refresh docker data, or move old graph driver to the new path. 

Creating a FS link (joint) will also work.

**Comment by StefanScherer** [comment]
@sitano Thanks for the deep investigation! The change is both in latest docker and also in the just released docker 1.12.0 available at GitHub release page https://github.com/docker/docker/releases/tag/v1.12.0 and there the Windows 64bit zip: https://get.docker.com/builds/Windows/x86_64/docker-1.12.0.zip

As Windows is still a tech preview we have to ship around these obstacles.

The symlink/joint is a good idea that could be part of the update script to fetch the nightly version.

I think in a few weeks the official download of the docker exes would be more up to date and this migration step is obsolete by building a new packer basebox again.

**Comment by StefanScherer** [comment]
@sitano There are two script to update docker engine to nightly or 1.12.0 in the repo renaming the directory to image\windowsfilter. :-)
