### ISSUE TITLE
Error upon vagrant up Mac OSX

### ISSUE THREAD

**Issue by scheung38** [StefanScherer/docker-windows-box#42]
Catalina 10.15.4

$ git clone https://github.com/StefanScherer/docker-windows-box.git && cd docker-windows-box   

$ vagrant up
 
==> default: Successfully added box 'StefanScherer/windows_2019' (v2020.02.26) for 'virtualbox'!
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The 'reload' provisioner could not be found.

How to fix this thanks

**Comment by StefanScherer** [comment]
These Vagrantfiles often use the reload plugin. 

You can install it with

```
vagrant plugin install vagrant-reload
```
