### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by jmbeach** [StefanScherer/docker-windows-box#7]
Probably worth adding to the readme that `docker-windows-box` is dependent on:
- VMware Player
- VMware Vix (for vmrun command)
- vmware-vdiskmanager command (which I'm not sure where the proper place to download that)

**Comment by StefanScherer** [comment]
@jmbeach Thanks for the suggestion. I don't have experience with VMware Player for the last three years.

The `docker-windows-box` Vagrant environment can be used with three Hypervisors
- VMware Fusion (Pro) (on Mac) or VMware Workstation (Pro) (on Windows or Linux)
- VirtualBox on Mac/Windows/Linux
- Hyper-V on Windows 10

The Vagrant basebox can be built with Packer for VMware/VirtualBox or with a patched Packer version for Hyper-V as there is a Pull Request in progress to bring that into upstream Packer.

**Comment by jmbeach** [comment]
How would you run packer for VirtualBox? I'm not very familiar with any of this. I want to start playing with Docker, but don't have anything but my laptop to play with so I figured I'd try to run Windows Server 2016 on a virtual machine and play docker images from it.

Either way. I was actually trying to run `packer build` assuming it was compatible with VMware Player and it gave me errors about not having the vmrun utility and the vmware-vdiskmanager utility, now the build appears to be working after I installed them.

**Comment by StefanScherer** [comment]
@jmbeach ok, have a look at this blog post https://stefanscherer.github.io/setup-local-windows-2016-tp5-docker-vm/ 

I'm used to the command line, especially a PowerShell terminal. So these would be the steps I would do on a Windows machine that does not have the tools I need.

Step 1: Install Chocolatey - https://chocolatey.org

```
iex (wget 'https://chocolatey.org/install.ps1' -UseBasicParsing)
```

Step 2: Install Packer

```
choco install -y packer
```

Step 3: Install Vagrant (I suggest version 1.8.1 at the moment)

```
choco install -y vagrant -version 1.8.1
```

Step 4: Install VirtualBox 5.0.x (I think 5.1 does not work with Vagrant 1.8.1) if not already installed

```
choco install -y virtualbox -version 5.0.24.108355
```

I'll try to figure out if some TP5 Vagrant boxes can be provided via Atlas form Hashicorp https://atlas.hashicorp.com/boxes/search
This would simplify the tutorial removing the step 2 and of course the `packer build` step of the blog post.

**Comment by StefanScherer** [comment]
@jmbeach If you are afraid of such tools you might have a look at http://blog.couchbase.com/2016/april/windows-server-2016-virtualbox-docker and do the steps with your VMware Player. Might work as well.

**Comment by jmbeach** [comment]
Very good blog post. You should link it in the readme

**Comment by jmbeach** [comment]
I think `packer build --only=virtualbox-iso windows_2016_docker.json` is what I was looking for. Thanks for your work on this.

**Comment by jmbeach** [comment]
The packer build still failed for me, but not until pretty far into the setup. I ran it in debug and got it to at least install updates before I quit packer and now I'm packaging the box manually with vagrant. Either way, I think I'll be set if I just use your packer config manually. Feel free to close this
